deployment:
  replicas: 2
  image:
    owner: ramsjenu
    repository: pythonflaskapp
    tag: 8527365d0c254a2198ff603d50c907315e6aa60b
  container:
    name: pythonflaskapp
    port: 80
service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 31507
