deployment:
  replicas: 0
  image:
    owner: ramsjenu
    repository: pythonflaskapp
    tag: cdfedb34cc6aabe2268a28ba75f04a82b4c24e3f
  container:
    name: pythonflaskapp
    port: 80
service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 31507
