deployment:
  replicas: 2
  image:
    owner: ramsjenu
    repository: pythonflaskapp
    tag: 56b35f918bf1689b23db03e2cc18975ca7d93a24
  container:
    name: pythonflaskapp
    port: 80
service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 31508
